---
ansible_connection: local
ansible_network_os: nxos
ansible_user: "svc.dcmetroscript"
ansible_password: "Kp!@9z2@EdSp3F1p.^R"

VLAN:
  - {id: 1150, name: sjc05-evo-fed-workload, vni: 1001150, mcast: 239.0.0.55 }
  - {id: 1151, name: sjc05-evo-fed-ingress, vni: 1001151, mcast: 239.0.0.55 }
  - {id: 1152, name: sjc05-evo-fed-vtep, vni: 1001152, mcast: 239.0.0.55 }
#  - {id: 3943, name: eat1-nsxmgr-perimeter-sp, vni: 1003943, mcast: 239.0.8.29 }
#  - {id: 3944, name: eat1-nsxmgr-l2only-01, vni: 1003944, mcast: 239.0.8.29 }
#  - {id: 3945, name: eat1-nsxmgr-l2only-02, vni: 1003945, mcast: 239.0.8.30 }
#  - {id: 3946, name: eat1-nsxmgr-l2only-03, vni: 1003946, mcast: 239.0.8.30 }
#  - {id: 3947, name: eat1-nsxmgr-l2only-04, vni: 1003947, mcast: 239.0.8.30 }
#  - {id: 3948, name: eat1-dr-isilon-extnd, vni: 1003948, mcast: 239.0.8.30 }
#  - {id: 3949, name: eat1-cloud-infra-ops-esxi-mgmt, vni: 1003949, mcast: 239.0.8.30 }
#  - {id: 3856, name: eat1-cloudinfra-wld04-ingress08-LS, vni: 1003856, mcast: 239.0.8.12 }

SVIs:
  - {id: 1150, ipaddr:    10.188.164.253/24, descr:    sjc05-evo-fed-workload }
  - {id: 1151, ipaddr:    10.188.165.253/24, descr:    sjc05-evo-fed-ingress }
  - {id: 1152, ipaddr:    10.188.166.253/24, descr:    sjc05-evo-fed-vtep }
#  - {id: 3943, ipaddr:    10.200.33.253/26, descr:    eat1-nsxmgr-perimeter-sp }
#  - {id: 3856, ipaddr:    10.200.76.253/24, descr:    eat1-cloudinfra-wld04-ingress08-LS }
...
