---
- hosts: "ftp_copy"
  gather_facts: false
  tasks:

  - name: initiate file copy from device
    nxos_command:
      commands:
        - conf t
        - "copy ftp://dcmetro:VMware1!@10.128.39.7/n9000-epld.9.3.9.img bootflash: vrf management"

  - name: verify the file is in the bootflash
    nxos_command:
      commands:
        - "dir bootflash: | i n9000-epld.9.3.9.img"
    register: output
    tags: verify

  - name: save config to /etc/ansible/backups/ftpcopy_eldp-sc2
    copy:
      content: "{{output.stdout[0]}}"
      dest: "/etc/ansible/backups/ftpcopy_eldp-sc2/{{inventory_hostname}}.txt"
    tags: verify
...
