---
- hosts: "ITCM-12596"
  gather_facts: false

  tasks:
  - name: Create checkpoint 
    nxos_command:
      commands: checkpoint Jun20 description Checkpoint created for ITCM-12596
  - name: Change Description for TEMP VLANs
    nxos_vlan:
      vlan_id: "{{ item.id }}"
      name: "{{ item.name }}"
    with_items: "{{ VLANDESC1 }}"
  - name: Adding SCDC2 Stretched Vlans to N9k Fabric
    nxos_vlan:
      vlan_id: "{{ item.id }}"
      name: "{{ item.name }}"
      mapped_vni: "{{ item.vni }}"
    with_items: "{{ VNI1 }}"
  - name: Configure BUM SCDC2 Stretched Vlans
    nxos_vxlan_vtep_vni:
      interface: nve1
      vni: "{{ item.vni }}"
      multicast_group: "{{ item.multicast }}"
    with_items: "{{ VNI1 }}"
  - name: Update BUM on the remaining VLANs, Task 1->remove VNI on NVE1 Int.
    nxos_vxlan_vtep_vni:
      interface: nve1
      vni: "{{ item.vni }}"
      state: absent
    with_items: "{{ NEWVNI1 }}"
  - name: Update BUM on the remaining VLANs, Task 2->Configure new BUM
    nxos_vxlan_vtep_vni:
      interface: nve1
      vni: "{{ item.vni }}"
      multicast_group: "{{ item.multicast }}"
    with_items: "{{ NEWVNI1 }}"
  - name: Remove un-used VLANs in WDC. Task 1-> remove VNI on the NVE1 Int.
    nxos_vxlan_vtep_vni:
      interface: nve1
      vni: "{{ item.vni }}"
      state: absent
    with_items: "{{ DELVNI1 }}"
  - name: Remove all un-used VLANs in WDC. Task 2-> Remove L2 VLANs
    nxos_vlan:
      vlan_id: "{{ item.id }}"
      state: absent
    with_items: "{{ DELVNI1 }}"
  - name: Save Config
    nxos_command:
      commands:
        - copy run start
...
