---
- hosts: "ITCM-45585"
  gather_facts: false

  tasks:
  - name: Adding L2 Vlan
    nxos_vlan:
      vlan_id: "{{ item.id }}"
      name: "{{ item.name }}"
      mapped_vni: "{{ item.vni }}"
    with_items: "{{ VLAN }}"
    tags: vni
  - name: Add VNI to NVE Interface
    nxos_vxlan_vtep_vni:
      interface: nve1
      vni: "{{ item.vni }}"
      multicast_group: "{{item.mcast }}"
      state: present
    with_items: "{{ VLAN }}"
    tags: vni
  - name: Configure the SVI
    nxos_command:
      commands:
        - config terminal
        - "interface vlan {{ item.id }}"
        - vrf member CORP
        - no shutdown
        - "ip address {{ item.ipaddr }}"
        - "description {{ item.descr }}"
        - mtu 9216
        - no ip redirects
        - no ipv6 redirects
        - fabric forwarding mode anycast-gateway
    with_items: "{{ SVIs }}"
    tags: svi
  - name: Save Config
    nxos_command:
      commands:
        - copy run start
...
