---
- hosts: "n9k-license"
  gather_facts: false

  tasks:
  - name: n9k-version
    nxos_command:
      commands:
        - "sh license host-id"
    register: config
    tags: version
  - name: save config to /etc/ansible/backups/license
    copy:
      content: "{{config.stdout[0]}}"
      dest: "/etc/ansible/backups/license/{{inventory_hostname}}.txt"
    tags: version
...
