---
- hosts: "newn9ks"
  gather_facts: false

  tasks:
  - name: Enable features
    nxos_feature:
      feature: "{{ item }}"
      state: enabled
    with_items: "{{ features }}"
  - name: Configure Interfaces
    nxos_interface:
      aggregate:
        - { name: Loopback0, description: BGP/OSPF Router-ID }
        - { name: Loopback1, description: Anycast VTEP }
        - { name: Ethernet1/49, mtu: 9216, description: n9k01-spine-eat1 Eth1/29 }
        - { name: Ethernet1/50, mtu: 9216, description: n9k02-spine-eat1 Eth1/29 }
        - { name: Ethernet1/55, mtu: 9216, description: n9k01-spine-eat1 Eth2/29 }
        - { name: Ethernet1/56, mtu: 9216, description: n9k02-spine-eat1 Eth2/29 }
    tags: ips
  - name: Configure IPs
    nxos_l3_interface:
      aggregate:
        - { name: Loopback0, ipv4: 10.250.206.63/32 }
        - { name: Loopback1, ipv4: 10.250.206.64/32 }
        - { name: Ethernet1/49, ipv4: 10.250.204.225/31 }
        - { name: Ethernet1/50, ipv4: 10.250.204.233/31 }
        - { name: Ethernet1/55, ipv4: 10.250.204.227/31 }
        - { name: Ethernet1/56, ipv4: 10.250.204.235/31 }
    tags: ips
  - name: Configure Secondary IP
    nxos_config:
      lines:
        - ip address 10.250.206.216/32 secondary
      parents: interface loopback1
    tags: ips
  - name: Configure VxLAN Overlay
    nxos_evpn_global:
      nv_overlay_evpn: true
    tags: nv
  - name: Configure Anycast GW
    nxos_overlay_global:
      anycast_gateway_mac: 6666.6666.6666
    tags: gw
  - name: Configure VRF
    nxos_vrf:
      vrf: "{{ item.vrf }}"
      rd: "{{ item.rd }}"
      vni: "{{ item.vni }}"
    with_items:
      - "{{ VRFs }}"
  - name: Configure IPv4 VRF RTs
    nxos_vrf_af:
      vrf: "{{ item.vrf }}"
      afi: ipv4
      route_target_both_auto_evpn: true
    with_items:
      - "{{ VRFs }}"
  - name: Configure IPv6 VRF RTs
    nxos_vrf_af:
      vrf: "{{ item.vrf }}"         
      afi: ipv6
      route_target_both_auto_evpn: true         
    with_items:
      - "{{ VRFs }}"
  - name: Configure VTEP
    nxos_vxlan_vtep:
      interface: nve1
      host_reachability: true
      shutdown: false
      source_interface: Loopback1
    tags: vtep
  - name: Configure VTEP association
    nxos_vxlan_vtep_vni:
      interface: nve1
      vni: "{{ item }}"
      assoc_vrf: true
    with_items:
      - "9999"
      - "9898"
      - "9696"
    tags: vtep
  - name: Configure OSPF
    nxos_ospf_vrf:
      ospf: "65270"
      router_id: 10.250.206.63
      timer_throttle_spf_start: "100"
      timer_throttle_spf_hold: "500"
      timer_throttle_spf_max: "5000"
      timer_throttle_lsa_start: "100"
      timer_throttle_lsa_hold: "500"
      timer_throttle_lsa_max: "5000"
      vrf: default
    tags: ospf
  - name: Configure OSPF Interfaces
    nxos_interface_ospf:
      interface: "{{ item }}"
      ospf: 65270
      area: "0"
    with_items: 
      - "{{ Underlay_Interfaces }}"
    tags: ospf
  - name: Configure OSPF Network Type
    nxos_interface_ospf:
      interface: "{{ item }}"
      ospf: 65270
      area: 0
      network: point-to-point
    with_items: 
      - "{{ OSPF_Type }}"
    tags: ospf
  - name: Configure PIM Interfaces
    nxos_pim_interface:
      interface: "{{ item }}"
      sparse: true
    with_items: 
      - "{{ Underlay_Interfaces }}"
    tags: pim
  - name: Configure RP
    nxos_pim_rp_address:
      rp_address: 10.250.206.200
      group_list: 239.0.0.0/16
    tags: pim
  - name: Configure SSM
    nxos_pim:
      ssm_range: default
    tags: pim
  - name: Configure BGP
    nxos_bgp:
      asn: "{{ asn }}"
      router_id: 10.250.206.63
      state: present
    tags: bgp
  - name: Configure BGP Default AFI
    nxos_bgp_af:
      asn: "{{ asn }}"
      vrf: default
      afi: l2vpn
      safi: evpn
      maximum_paths_ibgp: "4"
      additional_paths_send: true
      additional_paths_receive: true
      additional_paths_selection: BGP_Multipath
    tags: bgp
  - name: Configure BGP Tenant
    nxos_bgp_af:
      asn: "{{ asn }}"
      vrf: CORP
      afi: ipv4
      safi: unicast
      advertise_l2vpn_evpn: true
      maximum_paths_ibgp: 4
      redistribute: [['direct', 'CONNECTED']]
    tags: bgp
  - name: Configure iBGP Neighbor
    nxos_bgp_neighbor:
      asn: "{{ asn }}"
      neighbor: "{{ item.neighbor }}"
      remote_as: "{{ item.remote_as }}"
      description: "{{ item.description }}"
      update_source: "{{ item.update_source }}"
      timers_keepalive: "3"
      timers_holdtime: "10"
    with_items:
      - "{{ bgp_neighbors }}"
    tags: bgp
  - name: Configure iBGP Neighbor L2VPN
    nxos_bgp_neighbor_af:
      asn: "{{ asn }}"
      neighbor: "{{ item.neighbor }}"
      afi: l2vpn
      safi: evpn
      send_community: both
    with_items:
      - "{{ bgp_neighbors }}"
    tags: bgp
...
