---


- name:               Build APIC Configuration from Scratch
  hosts:              apic1
  connection:         local
  gather_facts:       no
  vars:
    apic_info:        &apic_info
      host:           "10.188.224.100"
      username:       "admin"
      password:       "VMware1!"

    shared_vars:
      descr:                    "Created by Ansible"

    vlan_pools:
      allocMode:                "static"
      vlanName:                 "all_vlans"
      vlanFrom:                 "vlan-2000"
      vlanTo:                   "vlan-2501"

    cdp_policy:
      adminSt:                  "enabled"
      cdpPolicyName:            "cdp-enabled"

    phys_dom:
      physDomName:              "physical_servers"

    aaep:
      aaepName:                 "all_vlans"

    intf_policies:
    - "ESX_Hosts"
    - "Linux_Hosts"
    - "Windows_Hosts"

    ifPolicyLeafProfileNames:
    - Leaf_101
    - Leaf_102
    - Leaf_103
    - Leaf_104
    - Leaf_105
    - Leaf_106
    - Leafs_101_and_102
    - Leafs_103_and_104
    - Leafs_105_and_106

    interfaceSelectors:
    - ifPolicyLeafProfileName: Leafs_101_and_102
      intf_policy: Linux_Hosts
      fromCard: '1'
      fromPort: '1'
      toCard: '1'
      toPort: '48'

    swPolicyLeafProfiles:
    - swPolicyLeafProfileName: Leaf_101
      leafName: Leaf-101
      leafId: '101'
    - swPolicyLeafProfileName: Leaf_102
      leafName: Leaf-102
      leafId: '102'
    - swPolicyLeafProfileName: Leaf_103
      leafName: Leaf-103
      leafId: '103'
    - swPolicyLeafProfileName: Leaf_104
      leafName: Leaf-104
      leafId: '104'
    - swPolicyLeafProfileName: Leaf_105
      leafName: Leaf-105
      leafId: '105'
    - swPolicyLeafProfileName: Leaf_106
      leafName: Leaf-106
      leafId: '106'
    - swPolicyLeafProfileName: Leafs_101_and_102
      leafName: Leaf-101
      leafId: '101'
    - swPolicyLeafProfileName: Leafs_101_and_102
      leafName: Leaf-102
      leafId: '102'
    - swPolicyLeafProfileName: Leafs_103_and_104
      leafName: Leaf-103
      leafId: '103'
    - swPolicyLeafProfileName: Leafs_103_and_104
      leafName: Leaf-104
      leafId: '104'
    - swPolicyLeafProfileName: Leafs_105_and_106
      leafName: Leaf-105
      leafId: '105'
    - swPolicyLeafProfileName: Leafs_105_and_106
      leafName: Leaf-106
      leafId: '106'

    vrfs:
    - tenantName: common
      vrfName: vrf-01

    bridgeDomains:
    - bdName: 192.168.100.0_24
      tenantName: common
      vrfName: vrf-01
    - bdName: 192.168.101.0_24
      tenantName: common
      vrfName: vrf-01

    bdSubnets:
    - bdName: 192.168.100.0_24
      tenantName: common
      gwAddress: 192.168.100.1
      mask: 24
    - bdName: 192.168.101.0_24
      tenantName: common
      gwAddress: 192.168.101.1
      mask: 24

    tenants:
    - tenantName: Demo

    appProfiles:
    - apName: WordPress
      tenantName: Demo

    epgs:
    - epgName: WebServers
      tenantName: Demo
      apName: WordPress
      bdName: 192.168.100.0_24
    - epgName: DbServers
      tenantName: Demo
      apName: WordPress
      bdName: 192.168.101.0_24

    staticPorts:
    - nodeID: 101
      path: eth1/11
      vlanID: 2011
      tenantName: Demo
      apName: WordPress
      epgName: WebServers
    - nodeID: 101
      path: eth1/12
      vlanID: 2012
      tenantName: Demo
      apName: WordPress
      epgName: WebServers
    - nodeID: 101
      path: eth1/13
      vlanID: 2013
      tenantName: Demo
      apName: WordPress
      epgName: DbServers

  tasks:

  # Delete Tenant
  - name: Delete Tenant(s)
    aci_tenant:
      <<: *apic_info
      validate_certs: no
      tenant: "{{item.tenantName}}"
      state: absent
    with_items:
      "{{tenants}}"
    loop_control:
      pause: .5

  # Delete Bridge Domain(s)
  - name: Delete Bridge Domain(s)
    aci_bd:
      <<: *apic_info
      validate_certs: no
      tenant: "{{item.tenantName}}"
      bd: "{{item.bdName}}"
      vrf: "{{item.vrfName}}"
      state: absent
    with_items:
      "{{bridgeDomains}}"
    loop_control:
      pause: .5

  # Delete VRF
  - name: Delete VRF(s)
    aci_vrf:
      <<: *apic_info
      validate_certs: no
      vrf: "{{item.vrfName}}"
      tenant: "{{item.tenantName}}"
      policy_control_preference: enforced
      policy_control_direction: ingress
      state: present
    with_items:
      "{{vrfs}}"
    loop_control:
      pause: .5

  # Delete Switch Policy Leaf Profiles
  - name:             Delete Switch Policy Leaf Profiles
    aci_rest:
      <<: *apic_info
      validate_certs: no
      use_proxy:      no
      path:           /api/mo/.json
      method:         post
      content:
        infraNodeP:
          attributes:
            dn: uni/infra/nprof-{{item.swPolicyLeafProfileName}}
            status: deleted
          children: []
    with_items:
      "{{swPolicyLeafProfiles}}"
    loop_control:
      pause: .5

  # Delete Interface Policy Leaf Profiles
  - name:             Delete Interface Policy Leaf Profiles
    aci_rest:
      <<: *apic_info
      validate_certs: no
      use_proxy:      no
      path:           /api/mo/.json
      method:         post
      content:
        infraAccPortP:
          attributes:
            dn: uni/infra/accportprof-{{item}}
            status: deleted
          children: []
    with_items:
      "{{ifPolicyLeafProfileNames}}"
    loop_control:
      pause: .5

  # Delete Interface Policy Groups
  - name:             Delete Interface Policy Groups
    aci_rest:
      <<: *apic_info
      validate_certs: no
      use_proxy:      no
      path:           /api/mo/.json
      method:         post
      content:
        infraAccPortGrp:
          attributes:
            dn: uni/infra/funcprof/accportgrp-{{item}}
            status: deleted
          children: []
    with_items:
      "{{intf_policies}}"

  # Delete AAEP
  - name:             Delete Attachable Access Entity Profile
    aci_rest:
      <<: *apic_info
      validate_certs: no
      use_proxy:      no
      path:           /api/mo/.json
      method:         post
      content:
        infraAttEntityP:
          attributes:
            dn: uni/infra/attentp-{{aaep.aaepName}}
            status: deleted
          children: []

  # Delete PhysDom
  - name:             Delete Physical Domain
    aci_rest:
      <<: *apic_info
      validate_certs: no
      use_proxy:      no
      path:           /api/node/mo/uni/phys-{{phys_dom.physDomName}}.json
      method:         delete

  # Delete CDP Policy
  - name:             Delete CDP Policy
    aci_rest:
      <<: *apic_info
      validate_certs: no
      use_proxy:      no
      path:           /api/mo/.json
      method:         post
      content:
        cdpIfPol:
          attributes:
            dn: uni/infra/cdpIfP-{{cdp_policy.cdpPolicyName}}
            status: deleted
          children: []

  # Delete VLAN Pools
  - name:             Delete VLAN Pools
    aci_rest:
      <<: *apic_info
      validate_certs: no
      use_proxy:      no
      path:           /api/mo/.json
      method:         post
      content:
        fvnsVlanInstP:
          attributes:
            dn: uni/infra/vlanns-[{{vlan_pools.vlanName}}]-static
            status: deleted
          children: []
...
